export { default as Anchor } from "./anchor"
export { default as Download } from "./download"
export { default as Footer } from "./footer"
export { default as Head } from "./head"
export { default as Layout } from "./layout"
export { default as Menu } from "./menu"
export { default as Nav } from "./nav"
export { default as Social } from "./social"
export { default as Video } from "./video"

// Sections
export { default as About } from "./sections/about"
export { default as Apps } from "./sections/apps"
export { default as Contact } from "./sections/contact"
export { default as Splash } from "./sections/splash"
